### ISSUE TITLE
Support for KAPA library prep, Rapid analysis (dragen) and GATK4 pipeline 

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/EGCG-Project-Management#109]
We need to 
 - [ ] obtain documentation of the KAPA library preparation from the lab,
 - [ ] Document Rapid analysis pipeline
 - [ ] Document GATK4 pipeline

**Comment by mwhamgenomics** [comment]
Paragraphs to add:

- GATK4 var calling
  - human and non-human produce the same deliverables, so can have 1 paragraph for both
  - we don't need a GATK4 QC paragraph because it would be the same as for GATK4
- rapid processing
- KAPA library prep

Test cases to add:

- GATK4 var calling with KAPA and rapid

**Comment by tcezard** [comment]
closed #117
