### ISSUE TITLE
Fix configuration mess

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/EGCG-Project-Management#51]
There are elements in the configuration file that have been duplicated over time and are now appearing multiple time.
The duplicates should be searched and removed
one example is delivery destination which appears in:
 -  in [samples](https://github.com/EdinburghGenomics/EGCG-Project-Management/blob/dc02cc04d4badb07901369e077e09a295e9a701c/project_report/__init__.py#L57)
 - in the [root](https://github.com/EdinburghGenomics/EGCG-Project-Management/blob/851cdcbfd4ac5af8c9941157c2972f9e610bbc87/bin/confirm_delivery.py#L169)
 - in [delivery --> dest](https://github.com/EdinburghGenomics/EGCG-Project-Management/blob/94f57123802a30d8eb7e3c679fced53ad3aa0128/bin/deliver_reviewed_data.py#L69)

**Comment by mwhamgenomics** [comment]
At this point, the main duplicate config references are:
- Email configurations - will need to change EGCG-Core to allow more flexible configuration, since the receipient list is more likely to change than the other parameters
- `sample -> delivery_source` and `sample -> delivery_dest` - these require changes in Analysis-Driver

**Comment by mwhamgenomics** [comment]
Opened https://github.com/EdinburghGenomics/Analysis-Driver/issues/355.

**Comment by tcezard** [comment]
This has been sorted here and new issue opened in Analysis driver
